#!/bin/sh
BUILD_DIR='./build'
if [ -d ${BUILD_DIR} ]; then
    if [ "$1" = "new" ]; then
	    rm -rf ${BUILD_DIR}
    else
        ninja -C ${BUILD_DIR} && exit
    fi
fi
meson . ${BUILD_DIR} \
    -Dbuildtype=debugoptimized \
&& ninja -C ${BUILD_DIR}
